In [4]:
#Num0y library
import numpy as np

first_numpy_array = np.array([1,2,3,4])
print(first_numpy_array)

[1 2 3 4]


In [6]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#array with empty
array_with_empty = np.empty((2,3))
array_with_empty

array([[1.72723371e-077, 1.49933578e-315, 1.48219694e-323],
       [0.00000000e+000, 0.00000000e+000, 4.17201348e-309]])

In [11]:
#array with arange method
np_arange = np.arange(12)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
#reshape array
np_arange.reshape(3,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
#linspace for linearly (equal) spaced data elements
np_linspace = np.linspace(1,6,5)
np_linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [25]:
#1D array
oneD_array = np.arange(15)
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
#2D array
twoD_array = oneD_array.reshape(5,3)
twoD_array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [34]:
#3D array
threeD_array = np.arange(27).reshape(3,3,3)
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])